### ISSUE TITLE
Best test for skewed sample sizes 

### ISSUE THREAD

**Issue by Somebodyatthdoor** [statdivlab/happi#53]
Hi,

Me again :) I am trying to work out what the best approach would be for testing two groups with very different numbers of samples. Sorry, my stats knowledge is not what it should be and I am struggling to work this out for myself. 

The vignette says that for sample sizes of >100 the standard happi test should work, but that the non-parametric test is better for smaller sample sizes. I am using happi to test for functions that are enriched in bacterial genomes that are significantly more abundant in my test group (as identified by ancom-bc2). This can end up being quite a small proportion of the total genomes: for example 500 genomes in total, with only 30 that are more abundant in my test group. In this sort of situation, would it be better to use the non-parametric test, or would it not matter in your opinion? 

Thanks for all your help,
Laura

**Comment by adw96** [comment]
Hi Laura! Thanks for your continued interest in happi. We are glad to support you. 

A few things to consider:

I strongly discourage you from using ancom-bc2 (or any differential abundance method) to choose which functions you'd like to test as differentially present. So, while I can answer the question you asked, I feel it is my professional responsibility to caution against this approach. The reason for this is that your differential abundance method uses the data to give you a list of what to test, and then happi uses that same data to test for differential evidence. This general problem is called post-selection inference, and in practice it means that your happi p-values won't be valid, and you shouldn't trust them 😿 They will be too small, giving you an inflated probability of rejecting (eg more than 5% -- because you only looked at what's most likely to be rejected!)

A better approach would be to perform two analyses: one differential abundance analysis (which gives you your top functional hits for DA), and one differential presence analysis (which gives you your top functional hits for DP). You can then correct the false discovery rate of each analysis individually. I like this better as it doesn't involve conditioning on one output to decide what to test in the next step. DA and DP are asking two different scientific questions, and I think it's reasonable to ask both in a given analysis -- as long as you set out to ask them both from the outset. 

To answer the question that you asked, I would always recommend the nonparametric test where possible given computational considerations. This may be prohibitive in, e.g., testing tens of thousands of functions. That said, if you're able to run it, I would trust those p-values more than the asymptotic test in your case. 

And finally, because I can't help it, ANCOM-BC2 has lots of problems that are addressed by [radEmu](https://github.com/statdivlab/radEmu/), including ignoring precision information when CLR-transforming, choosing an arbitrary pseudo-count, and error-rate control. I'd love you to consider using it in a future analysis.

**Comment by Somebodyatthdoor** [comment]
Hi @adw96,

Sorry just wanted to check I understand what you are saying.  For your statement "I strongly discourage you from using ancom-bc2 (or any differential abundance method) to choose which functions you'd like to test as differentially present", I may be misunderstanding but I don't think this is what I'm doing. I am not selecting functions using ANCOM-BC2 (I am using all functions detected in my genomes), I am using ANCOM-BC2 to split my genomes into groups, in this case genomes that are significantly more abundant in samples that come from vaccinated animals (according to ANCOM-BC2) vs. genomes that are not significantly more abundant in samples that come from vaccinated animals. Then using happi to test differences in functions between these two groups. I would have thought that this wouldn't lead to post-selection inference problems, as ANCOM-BC2 and happi are using different data: ANCOM-BC2 is using genome abundance data (no function data), and happi is using presence/absence of functions data (no genome abundance data). 

Or does this still lead to the same problem (or indeed different problems)? If so, then I'm not entirely sure what would be the best way to approach this, because I need to do some kind of abundance analysis to work out which genomes are more abundant in one group versus another before I can do my functional analysis, my research question being: "Are certain functions more common in bacteria that are more abundant in vaccinated animals?". I have tried running happi using multiple-functions with FDR corrections, and it does seem to be giving me sensible results. 

I have quite good computational resources so I will use the nonparametric test from now on. I'll also give radEmu a gander for my future analyses, though I'll stick to ANCOM-BC2 for this study. 

Cheers,
Laura

**Comment by adw96** [comment]
Thanks for clarifying, Laura. I hadn't considered this approach before, but it seems reasonable. 

Best wishes with your study, and let us know if you have any more questions by opening a new issue.
